"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WindowEventEnum = void 0;
var WindowEventEnum;
(function (WindowEventEnum) {
    WindowEventEnum["PAGE_TITLE_UPDATED"] = "page-title-updated";
    WindowEventEnum["CLOSE"] = "close";
    WindowEventEnum["CLOSED"] = "closed";
    WindowEventEnum["SESSION_END"] = "session-end";
    WindowEventEnum["UNRESPONSIVE"] = "unresponsive";
    WindowEventEnum["RESPONSIVE"] = "responsive";
    WindowEventEnum["BLUR"] = "blur";
    WindowEventEnum["FOCUS"] = "focus";
    WindowEventEnum["SHOW"] = "show";
    WindowEventEnum["HIDE"] = "hide";
    WindowEventEnum["READY_TO_SHOW"] = "ready-to-show";
    WindowEventEnum["MAXIMIZE"] = "maximize";
    WindowEventEnum["UNMAXIMIZE"] = "unmaximize";
    WindowEventEnum["MINIMIZE"] = "minimize";
    WindowEventEnum["RESTORE"] = "restore";
    WindowEventEnum["WILL_RESIZE"] = "will-resize";
    WindowEventEnum["RESIZE"] = "resize";
    WindowEventEnum["WILL_MOVE"] = "will-move";
    WindowEventEnum["MOVE"] = "move";
    WindowEventEnum["MOVED"] = "moved";
    WindowEventEnum["ENTER_FULL_SCREEN"] = "enter-full-screen";
    WindowEventEnum["LEAVE_FULL_SCREEN"] = "leave-full-screen";
    WindowEventEnum["ENTER_HTML_FULL_SCREEN"] = "enter-html-full-screen";
    WindowEventEnum["LEAVE_HTML_FULL_SCREEN"] = "leave-html-full-screen";
    WindowEventEnum["ALWAYS_ON_TOP_CHANGED"] = "always-on-top-changed";
    WindowEventEnum["APP_COMMAND"] = "app-command";
    WindowEventEnum["SCROLL_TOUCH_BEGIN"] = "scroll-touch-begin";
    WindowEventEnum["SCROLL_TOUCH_END"] = "scroll-touch-end";
    WindowEventEnum["SCROLL_TOUCH_EDGE"] = "scroll-touch-edge";
    WindowEventEnum["SWIPE"] = "swipe";
    WindowEventEnum["SHEET_BEGIN"] = "sheet-begin";
    WindowEventEnum["SHEET_END"] = "sheet-end";
    WindowEventEnum["NEW_WINDOW_FOR_TAB"] = "new-window-for-tab";
})(WindowEventEnum || (exports.WindowEventEnum = WindowEventEnum = {}));
//# sourceMappingURL=window-listener.enum.js.map