# This is a basic workflow to help you get started with Actions
name: 'Windows Build'

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    permissions:
      contents: read
    strategy:
      matrix:
        node-version: [24]

    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v7

    - name: Cache Node modules
      uses: actions/cache@v6
      with:
        # npm cache files are stored in ~/.npm
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Cache Electron binaries
      uses: actions/cache@v6
      with:
        path: |
          ${{ env.LOCALAPPDATA }}\electron\Cache
          ${{ env.LOCALAPPDATA }}\electron-builder\Cache
        key: ${{ runner.os }}-electron-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-electron-

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v7
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: npm ci

    - name: Check lint
      run: npm run lint

    - name: Install Playwright Browsers
      run: npx playwright@1.60.0 install --with-deps

    - name: Run headless unit test
      run: npm run test -- --reporters=default

    - name: Run headless e2e test
      run: npm run e2e

    - name: Build the app
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 15
        max_attempts: 3
        command: npm run electron:build
